default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 20101600
  host: localhost

development:
  <<: *default
  database: control_patrimony_development

test:
  <<: *default
  database: control_patrimony_test

production:
  <<: *default
  database: control_patrimony_production
  username: postgres
  password: 20101600